### ISSUE TITLE
Create SSH Tunnel Add-on

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/hass-addons#1]
Using the commands defined in oceanbuilders/ob-iac#12, create an add-on that has a switch that establishes and disconnects a tunnel from the Raspberry Pi in a pod to the remote AWS admin instance.

![image](https://user-images.githubusercontent.com/4229319/116823558-1002bd80-ab3a-11eb-8d59-e68588fce4ba.png)

It should forward ports 22, 22222 and 8123 to remote ports starting at 10000, and increment by 10 for each pod in the preceding order., e.g.

ssh -R 100000:127.0.0.1:22 -N -f scott@ec2-44-235-91-166.us-west-2.compute.amazonaws.com
ssh -R 100001:127.0.0.1:22222 -N -f scott@ec2-44-235-91-166.us-west-2.compute.amazonaws.com
ssh -R 100002:127.0.0.1:8123 -N -f scott@ec2-44-235-91-166.us-west-2.compute.amazonaws.com

The next would be:

ssh -R 10010:127.0.0.1:22 -N -f scott@ec2-44-235-91-166.us-west-2.compute.amazonaws.com
ssh -R 10011:127.0.0.1:22222 -N -f scott@ec2-44-235-91-166.us-west-2.compute.amazonaws.com
ssh -R 10012:127.0.0.1:8123 -N -f scott@ec2-44-235-91-166.us-west-2.compute.amazonaws.com

and so on..

The remote IP needs to be dynamically allocated when configured, e.g. next available, but must be static thereafter, so that when we want to connect to a pod from the admin server we know that port 10000 on the Sysadmin instance will connect to port 22 on Pod A and Port 10010 will connect to port 22 (ssh) on Pod B, and so forth.

When the switch is turned on in the add-on panel, it creates the ssh tunnel from the above, then disconnects them on shut down.

**Comment by olagalal** [comment]
Maybe this could help: https://github.com/Nossnevs/Nossnevs-Home-Assistant-Addons

**Comment by scottdear** [comment]
Need to connect w/ @scottdear re: public key issue.

**Comment by olagalal** [comment]
It worked for one user 'hass'
<img width="1019" alt="Screen Shot 2021-05-27 at 7 51 22 PM" src="https://user-images.githubusercontent.com/12789198/119873527-ec5a4980-bf24-11eb-988e-cfcbe7f7f03a.png">

**Comment by angiedear** [comment]
We need to wrap an add on to it in order to close issue.
